# Generated by Django 5.2.16 on 2026-07-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='energy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='stress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
