# Generated by Django 5.2.16 on 2026-07-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('meditation', 'Meditation'), ('breathing', 'Breathing'), ('sleep', 'Sleep'), ('exercise', 'Exercise'), ('nutrition', 'Nutrition'), ('journaling', 'Journaling'), ('music', 'Music'), ('social', 'Social'), ('growth', 'Growth'), ('general', 'General')], default='general', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('mood_min', models.IntegerField(blank=True, null=True)),
                ('mood_max', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
